### ISSUE TITLE
滚动截屏时，当滚动到页面有比较大的空白页时自动结束了，但有时这并不是想要的，这个能优化下这个阈值吗？比如截图时设置永不自动结束之类的，让遇到这类空白的长页也能一直截图下去

### ISSUE THREAD

**Issue by itq5** [xinhecuican/easy-capture#11]
**版本**

- 操作系统版本: 
- 程序版本：

**问题**
滚动截屏时，当滚动到页面有比较大的空白页时自动结束了，但有时这并不是想要的，这个能优化下这个阈值吗？比如截图时设置永不自动结束之类的，让遇到这类空白的长页也能一直截图下去
简要描述你的操作过程，最好可以
[log.txt](https://github.com/user-attachments/files/15873824/log.txt)
提供日志文件。日志文件在Data/Temp/log.txt

**Comment by xinhecuican** [comment]
按鼠标中键可以手动滚动
