### ISSUE TITLE
滚动截图无法完成

### ISSUE THREAD

**Issue by G1t-hub** [xinhecuican/easy-capture#12]
**版本**

- 操作系统版本: 10.0.19041.1
- 程序版本：0.8.8

**问题**
滚动截图功能若初始选区滚动方向长度大于非滚动方向长度，捕获后无法显示绘图窗口；手动关闭后再次触发滚动截图时选区窗口消失，程序概率崩溃。
附Log及crash dump: 
~~[crash.zip]~~

另外在此情况下剪贴板和Temp文件夹都找不到截图，希望可以为所有截图方式都增加捕获完成立即保存一个副本的功能，目前设置里只能设置全屏截图的保存目录。此外滚动截图的选区只能自动检测，希望可以像矩形截图一样手动选取。

**Comment by xinhecuican** [comment]
按住ctrl然后再左键选择可以手动选择区域

**Comment by xinhecuican** [comment]
我无法复现你的问题，滚动的时候尽量不要移动鼠标

**Comment by G1t-hub** [comment]
更换电脑安装0.8.9版本仍可复现。
简单来说就是找个高度比宽度大的竖屏窗口滚动截屏，而不是正常pc上的横屏窗口，截屏完成之后绘图窗口显示不出来，截图也无法完成及保存。

**Comment by xinhecuican** [comment]
你可以说一下是什么程序的窗口吗，我在chrome浏览器上竖屏没有问题

**Comment by G1t-hub** [comment]
> 你可以说一下是什么程序的窗口吗，我在chrome浏览器上竖屏没有问题

任意窗口，我试了微信内置浏览器和edge。我是Win10系统

**Comment by xinhecuican** [comment]
在你崩溃之后发一下日志，不要重新开启软件，日志是覆写的

**Comment by G1t-hub** [comment]
崩溃不好复现，之前的崩溃在上面的文件里有。不过绘图窗口不是没有，只是显示不了。任务栏缩略图是空白的。FYI
![blank](https://github.com/xinhecuican/easy-capture/assets/56796909/abc26c0e-2a70-4e5c-bc19-1e7d07fc491e)
另外在此之后不重启程序的话滚动截图功能就废掉了，触发后无选区只有绿色提示框

**Comment by xinhecuican** [comment]
我在微信的一个窗口上也发现这个问题了，我再调调

**Comment by G1t-hub** [comment]
稳定触发崩溃的方法：先如上文那样卡出空白窗口，使用缩略图右上角的X关掉，然后再次用快捷键触发滚动截图，程序随即闪退。
另外每次打开程序，使用快捷键触发第一次滚动截图时按Ctrl无法选区，再次选择滚动截图才可以。不知是什么原因。

**Comment by xinhecuican** [comment]
你再试试，微信应该可以截了。

**Comment by G1t-hub** [comment]
竖屏截图已经可以了。不过首次滚动截图无法选区的问题还是存在。您看看能不能复现，退出程序重新打开之后立刻按Ctrl+F3，这时候用Ctrl能不能选区？

**Comment by xinhecuican** [comment]
应该可以了现在
