### ISSUE TITLE
无法滚动截图，多屏截图无法撤销

### ISSUE THREAD

**Issue by 150wang69** [xinhecuican/easy-capture#13]
**版本**

- 操作系统版本: win11
- 程序版本：0.8.8

**问题**

简要描述你的操作过程，最好可以提供日志文件。日志文件在Data/Temp/log.txt

**Comment by 150wang69** [comment]
hmmm，卸载不彻底，需手动关闭并删除文件夹。

**Comment by xinhecuican** [comment]
安装卸载是用innosetup打包的，你可以试试用geek进行卸载
