### ISSUE TITLE
建议滚动截图中添加自定义窗口后在滚动截图

### ISSUE THREAD

**Issue by wolvth** [xinhecuican/easy-capture#5]
因为想截一个聊天窗口的滚动截图，发现无法实现。
找到了另一款软件，可以像自定义截图一样，先划一个区域，然后滚动截图。手动滚或者自动滚。

**Comment by xinhecuican** [comment]
已经实现了，按ctrl就行

**Comment by wolvth** [comment]
> 已经实现了，按ctrl就行

哦，我又试了下，是可以。但一些场景不行。win11 22H2，22621.2215
1，比如edge浏览器。
滚动截图全屏，选择最大的窗口（包含标题栏），点击后就直接截图全屏。
2，比如geek这个卸载软件，自动选择窗口，ctrl按住选择一个范围，都无效。
另一种特殊一点的场景
开着浏览器，再打开geek，geek的窗口在浏览器上。这时屏幕会有2个滚动条，自动选择滚动窗口，或者ctrl自定义也好，也是无效。

我找了另一款软件，他的逻辑是跟着鼠标选择滑动的窗口滚动条。不自动滚动，手动开始，手动滑动，手动停止。

**Comment by xinhecuican** [comment]
> > 已经实现了，按ctrl就行
> 
> 哦，我又试了下，是可以。但一些场景不行。win11 22H2，22621.2215 1，比如edge浏览器。 滚动截图全屏，选择最大的窗口（包含标题栏），点击后就直接截图全屏。 2，比如geek这个卸载软件，自动选择窗口，ctrl按住选择一个范围，都无效。 另一种特殊一点的场景 开着浏览器，再打开geek，geek的窗口在浏览器上。这时屏幕会有2个滚动条，自动选择滚动窗口，或者ctrl自定义也好，也是无效。
> 
> 我找了另一款软件，他的逻辑是跟着鼠标选择滑动的窗口滚动条。不自动滚动，手动开始，手动滑动，手动停止。

手动滚动是按ctrl选择区域后按**中键**，然后鼠标滚动完成之后按esc结束。这两个地方确实不行，我再修一修

**Comment by xinhecuican** [comment]
现在应该可以了
