### ISSUE TITLE
建议加上贴图和多屏截图的功能

### ISSUE THREAD

**Issue by only-wjt** [xinhecuican/easy-capture#8]
### 2、建议支持多平截图
目前多屏幕下只能识别到主屏幕，副屏幕无法截图
### 3、滚动截图还需优化
excel中滚动截图有些地方拼接还是有问题
而且滚动截图后，在截图最下方有半屏的空白界面

**Comment by xinhecuican** [comment]
如果滚动截图还有问题可以试试手动滚动，或者在截完之后再进行编辑

**Comment by only-wjt** [comment]
我测了下，贴图和滚动截图很好用了，excel中拼接的很完美了
就是那个多屏还是不行，我两个屏幕，只能主屏幕使用截图

**Comment by xinhecuican** [comment]
> 我测了下，贴图和滚动截图很好用了，excel中拼接的很完美了 就是那个多屏还是不行，我两个屏幕，只能主屏幕使用截图

我自己测试了多屏截图是可以的，一块笔记本屏幕和一块外接屏幕。

**Comment by only-wjt** [comment]
我的还是不行，会不会跟接口有关，我是通过hdmi接口外接的，或者是屏幕分辨率不一样导致的？

**Comment by xinhecuican** [comment]
我是dp接口，但是应该没关系吧，我两个屏幕分辨率是不一样的。要不删了重下试试？

**Comment by only-wjt** [comment]
> 我是dp接口，但是应该没关系吧，我两个屏幕分辨率是不一样的。要不删了重下试试？

试了下，原来截屏是跟随鼠标来判断截图哪个屏幕，我一直以为是snipaste那种，把两个屏幕当成一个画布去处理呢？
这样操作有个问题：就是我贴图之后，无法从一个屏幕转移到另外一个屏幕
