### ISSUE TITLE
win11 笔记本外接显示屏窗口内不支持滚动截屏

### ISSUE THREAD

**Issue by xhe-viavi** [xinhecuican/easy-capture#9]
**版本**
最新版
- 操作系统版本: 
- win11
- 程序版本：
- 最新版

**问题**
win11 笔记本外接显示屏窗口内不支持滚动截屏, 只能在笔记本自带桌面执行滚动截屏
个人感觉是只有触发截屏的快捷键只能触发截屏模式, 没有触发滚动截屏模式的快捷键, 导致点击滚动截屏模式只能在笔记本桌面触发

**Comment by xinhecuican** [comment]
目前可以试试切换到滚动截屏模式后再按Ctrl+F1

**Comment by xhe-viavi** [comment]
> 目前可以试试切换到滚动截屏模式后再按Ctrl+F1
可能我上面没说清楚, 目前问题就是 切换到截屏模式就自动锁定到笔记本桌面了, 没有办法在外接显示器上操作了
外接显示器目前只能支持普通截屏, 这个操作正常
